import { Metadata } from "next";
import Navigation from "../components/navigation";

export const metadata: Metadata = {
  title: { default: "NextJS-14", template: "%s | NextJS-14" },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
